# Generated by Django 3.0.8 on 2020-08-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.TextField()),
                ('book_title', models.TextField()),
                ('book_short_desc', models.TextField()),
                ('book_long_desc', models.TextField()),
                ('book_price', models.IntegerField()),
                ('book_img', models.ImageField(upload_to='pics')),
                ('book_publish_date', models.DateField()),
                ('book_offers', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.TextField()),
                ('book_title', models.TextField()),
                ('book_short_desc', models.TextField()),
                ('book_long_desc', models.TextField()),
                ('book_price', models.IntegerField()),
                ('book_img', models.ImageField(upload_to='pics')),
                ('book_publish_date', models.DateField()),
                ('book_offers', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.TextField()),
                ('book_title', models.TextField()),
                ('book_short_desc', models.TextField()),
                ('book_long_desc', models.TextField()),
                ('book_price', models.IntegerField()),
                ('book_img', models.ImageField(upload_to='pics')),
                ('book_publish_date', models.DateField()),
                ('book_offers', models.BooleanField(default=False)),
            ],
        ),
    ]
